### PR TITLE
Replace frontend with angular (part 1)

### PR DESCRIPTION
**Pull request by Daanra**
This is a first attempt and simplifying the front-end by introducing AngularJS. Our application is currently violating the MVC principle quite severely, introducing Angular will allow is to have a proper MVC set-up again.

This pull request only introduces a few angular components in the announcement section on the overview page. But it also contains a lot of file renames and moving of files as this was necessary (not just for Angular purposes). Therefore, this pull request should be merged into development as soon as possible even though the conversion towards Angular is far from complete.

### CODE REVIEW

**Comment by mircealungu** [comment]
@Daanra -- do you know why the Travis CI fails? 

I'm tempted to accept this one w/o review... 33K LOC is impossible to meaningfully review...

**Comment by NikolasHadjipanayi** [comment]
At the moment am trying to go through all the requests one by one.  If @mircealungu  you can wait for me will review this as well "soonish".

**Comment by mircealungu** [comment]
Thanks @NikolasHadjipanayi ! At 33K LOC, "soonish" is already amazing! One other thing that we could do is, given that this is such a large PR, just accept it, and do proper reviews for the future, smaller ones.

**Comment by Daanra** [comment]
@mircealungu This is an incremental PR based on the other PRs. So even though it says 33K line changes, it is actually spread over the other 3 PRs. If Nikolas merges these pull requests in chronological order then the number of line changes should drop for each PR. Each PR still has an average of 11K line changes each, so it is still way too much to properly review though. 

The build was failing because the code that fixes the CI was in a separate pull request and was only recently merged with development. I manually merged development back into this pull request so now some of the tests work. Many tests still fail, these tests fail due to recent changes which introduced more strict policies. For example, you can no longer insert an announcement with an empty title into the database. Some of the tests try to insert such items into our database and then fail because the database does not accept the data. All of these failing tests will need to be rewritten/changed but I will leave that to @NikolasHadjipanayi.

**Comment by NikolasHadjipanayi** [comment]
@Daanra @mircealungu  the LOC do not change as I merge pull requests this has probably something to do with the fact that the requests were not merged before proceeding with more work. I noticed that the majority of the files changed are duplicated through all the PRs and more than 90% are just indentation fixes. Indeed all this is too much to thoroughly review but am doing my best to identify the files with actual changes and review them.

**Pull request merged**
